parameters:
#    project_adminprincipal.example.class: projectAdmin\principalBundle\Example

services:
#    project_adminprincipal.example:
#        class: %project_adminprincipal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
